version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
      - 4317:4317
      - 4318:4318
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.72.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /tmp:/tmp
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - DD_API_KEY=${DD_API_KEY}
