receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${DD_API_KEY}
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, logging]